# Generated by Django 3.2.6 on 2021-08-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_alter_youtuber_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small_team', 'SM'), ('large_team', 'LM')], max_length=200),
        ),
    ]
