# Generated by Django 3.2.6 on 2021-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_alter_youtuber_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('sony', 'sony'), ('fuji', 'fuji')], max_length=250),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('cooking', 'cooking'), ('education', 'education'), ('programming', 'programming'), ('music', 'music')], max_length=250),
        ),
    ]
